### ISSUE TITLE
Get back to the last branch of two collections

### ISSUE THREAD

**Issue by AmalCHIKHAOUI** [Hypertopic/HyperGlosae#108]
When user is navigating inside a collection they should be always able to get back to the last branch from which they switch to.

- Edge case: when the users don't do any switch and stay in the original branch, we should navigate them to the first document (which can be the map)

#### Phase 1
- [x] Scenarios (Gherkin)
- [x] Mockups
- [x] Implementation strategy
#### Phase 2
- [x] Acceptance tests (Capybara)
- [ ] Implementation
#### Phase 3
- [ ] Screencast

**Comment by MCtzr** [comment]
**Mockups :**

First, suppose that we have these collections presented below :


![Image](https://github.com/Hypertopic/HyperGlosae/assets/91234392/9bf0b918-e08c-49e0-879d-e600f97f60a5)


The user is inside the collection 4, and he should be able to come back to the collection 3 branch.

We discussed about two solutions. The first one is a button on the top left of the document to come back to the last branch, with the name of the last collection.


![Image](https://github.com/Hypertopic/HyperGlosae/assets/91234392/2bb9f27e-82f5-4c43-bf17-4a53892ac059)


The second one is a history with the names of all the branches that the user switched from, on the bottom of the document (and the suggested documents). It can be a table or a list.


![Image](https://github.com/Hypertopic/HyperGlosae/assets/91234392/b5c0348b-b4ef-4725-b102-35fd838a7e1d)

**Comment by vallhallalm** [comment]
Co-authored-by : @kemplail @MCtzr 
**Implementation strategy:**

- [ ] Nous comptons créer un nouveau bouton flottant permettant de retourner vers la collection précédente.
- [ ] Pour retourner vers la collection précédente, nous garderons en mémoire les id de collection et de document pour recréer le lien associé à l'embranchement.
- [ ] Nous garderons également en mémoire le nom de la collection pour l'afficher à proximité du bouton.
- [ ] En terme de structure, ces informations seront stockées dans un tableau de tableau qui permettra de revenir en arrière dans plus d'une collection dans l'ordre des embranchements empruntés

**Comment by SebBac** [comment]
Voici la nouvelle proposition de Mockup par moi et @AmalCHIKHAOUI :

![Image](https://github.com/Hypertopic/HyperGlosae/assets/73548842/d8331077-968c-4f72-8c4e-ba2bc1ec8b79)

**Comment by benel** [comment]
Too bad this feature is not finished. It would have been very useful Monday (12/06).

**Comment by benel** [comment]
Mobile browsing should be kept out of the scope of this application (see #142).
